# Generated by Django 5.2.4 on 2026-07-03 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=200, verbose_name="Tiêu đề"
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("HAPPY", "Happy"),
                            ("SAD", "Sad"),
                            ("ANGRY", "Angry"),
                            ("CALM", "Calm"),
                            ("NEUTRAL", "neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("is_bookmark", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="journal_images/")),
                ("meta_data", models.JSONField(blank=True, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="journal.journal",
                    ),
                ),
            ],
        ),
    ]
