# Generated by Django 5.2.4 on 2026-07-03 16:35

import datetime
import django.db.models.deletion
import functools
import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "remind_every",
                    models.DurationField(
                        blank=True, default=datetime.timedelta(seconds=14400), null=True
                    ),
                ),
                (
                    "remind_at",
                    models.DateField(
                        blank=True,
                        default=functools.partial(
                            main.utils.default_time_helper,
                            *(datetime.timedelta(seconds=7200),),
                            **{}
                        ),
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField(default=datetime.timedelta(days=2))),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("best_streak", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "remind_every",
                    models.DurationField(
                        blank=True, default=datetime.timedelta(seconds=14400), null=True
                    ),
                ),
                (
                    "remind_at",
                    models.DateField(
                        blank=True,
                        default=functools.partial(
                            main.utils.default_time_helper,
                            *(datetime.timedelta(seconds=7200),),
                            **{}
                        ),
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "start_time",
                    models.DateTimeField(
                        default=functools.partial(
                            main.utils.default_time_helper,
                            *(datetime.timedelta(seconds=7200),),
                            **{}
                        )
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=functools.partial(
                            main.utils.default_time_helper,
                            *(datetime.timedelta(days=1),),
                            **{}
                        )
                    ),
                ),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAmount",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.task",
                    ),
                ),
                ("total_amout", models.PositiveIntegerField(default=1)),
                ("current_amount", models.PositiveIntegerField(default=0)),
                ("unit", models.CharField(max_length=25)),
            ],
            bases=("main.task",),
        ),
        migrations.CreateModel(
            name="TaskCheckBox",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.task",
                    ),
                ),
            ],
            bases=("main.task",),
        ),
        migrations.AddField(
            model_name="task",
            name="habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="main.habit",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
